version: '3.9'

services:
  app:
    build: .
    ports:
      - '3001:3001'
    environment:
      - MONGO_URI=mongodb://mongo:27017/vertice-test
      - JWT_SECRET=patitodeule
      - NODE_ENV=development
      - JWT_EXPIRES_IN=3600
      - PORT=3001
    depends_on:
      - mongo
    volumes:
      - .:/app
      - /app/node_modules

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
